// DXTimes のモック記事データ（デモ用・実データではありません）
export const articles = [
  {
    id: 1,
    title: '生成AIを業務に取り入れる最初の一歩',
    excerpt: '大きな導入計画の前に、小さく試して効果を測る。現場で始めやすいユースケースの選び方を解説します。',
    category: 'テクノロジー',
    author: '田中',
    publishedAt: '2026-05-28',
    readMinutes: 6,
    tags: ['生成AI', '業務改善'],
  },
  {
    id: 2,
    title: 'リモートワークで失われた雑談をどう取り戻すか',
    excerpt: '偶発的なコミュニケーションが減ったチームが、オンラインでつながりを取り戻すために試した工夫。',
    category: '働き方',
    author: '鈴木',
    publishedAt: '2026-05-21',
    readMinutes: 5,
    tags: ['リモートワーク', 'チーム'],
  },
  {
    id: 3,
    title: '社内ナレッジ検索を改善した事例',
    excerpt: '「探しても見つからない」を解消するために、検索の関連度とファセット絞り込みを見直した取り組み。',
    category: '事例',
    author: '佐藤',
    publishedAt: '2026-06-02',
    readMinutes: 8,
    tags: ['検索', 'ナレッジ', '事例'],
  },
  {
    id: 4,
    title: 'クラウド移行でコストを抑えるための勘所',
    excerpt: '闇雲な移行はかえって高くつく。配信・ストレージ構成を見直してムダを減らした実践メモ。',
    category: '事例',
    author: '高橋',
    publishedAt: '2026-05-15',
    readMinutes: 7,
    tags: ['クラウド', 'コスト'],
  },
  {
    id: 5,
    title: '2026年のWebパフォーマンス指標まとめ',
    excerpt: 'LCP・CLS をはじめ、いま見るべき表示速度の指標と、改善の優先順位の付け方を整理しました。',
    category: 'テクノロジー',
    author: '佐藤',
    publishedAt: '2026-06-08',
    readMinutes: 4,
    tags: ['パフォーマンス', 'Web'],
  },
  {
    id: 6,
    title: 'DXを止めない組織のつくり方',
    excerpt: '一度きりの号令で終わらせない。継続的に改善が回る組織の条件を、現場の声から考えます。',
    category: '働き方',
    author: '田中',
    publishedAt: '2026-04-30',
    readMinutes: 9,
    tags: ['DX', '組織'],
  },
]

export const categories = ['テクノロジー', '働き方', '事例', 'ニュース']
